# Generated by Django 5.1.4 on 2025-01-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('B', 'Borrador'), ('P', 'Publicado')], default='B', max_length=1),
        ),
    ]
