# Generated by Django 5.1.4 on 2025-01-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='blog.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_instrumento',
            field=models.CharField(choices=[('G', 'Guitarra'), ('B', 'Bajo')], default='G', max_length=1),
        ),
    ]
