# Generated by Django 5.1.4 on 2025-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comentario_autor_comentario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leyenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('historia', models.TextField()),
            ],
        ),
    ]
